[workspace]
members = ["extension/lib", "extension/bin/arma"]
resolver = "2"

[workspace.dependencies]
log = { version = "0.4.20", features = ["std"] }
arma-rs = { git = "https://github.com/BrettMayson/arma-rs", features = [
    "serde",
] }
crossbeam-channel = "0.5.11"

# dev-dependencies
pretty_assertions = { version = "1.2.1", features = ["unstable"] }

[profile.release]
lto = true
