[workspace]
members = ["extension/lib", "extension/bin/arma"]
resolver = "2"

[workspace.dependencies]
log = { version = "0.4.20", features = ["std"] }
arma-rs = { version = "1.10.5", features = ["serde"] }

[profile.release]
lto = true
